### ISSUE TITLE
Preferred host breaks isAllowed

### ISSUE THREAD

**Issue by WillSquire** [samclarke/robots-parser#27]
The `parsedUrl.hostname !== this._url.hostname` logic in `_getRule` doesn't work when the robot.txt's `host` is different from the request host and the sitemap uses robot.txt's preferred host.

When `robots.txt` sets a preferred host differently from the crawled request, i.e. 'example.com' instead of 'www.example.com', and the sitemap uses the preferred host like `example.com/about`, then `isAllowed` always fails.

A workaround is to replace the host in each sitemap link tested in `isAllowed` for the preferred host, and a fix would be to check the preferred host too, but to be honest, the logic is trying to be too clever.

**Comment by samclarke** [comment]
Thanks for reporting.

Nothing is stopping the preferred host from having a different robots.txt file. For example, `http://testing.example.com/robots.txt` might have the preferred host set to `http://www.example.com/` but not have the same robots.txt file at that location.

There's also nothing stopping the preferred host from being a completely different domain in which case the current robots.txt file definitely shouldn't apply.

I tried to see what other crawlers do, but I can't find anything about the preferred host directive. It looks like most crawlers either no longer use it or don't document their use of it.

The [Google robots.txt specification](https://developers.google.com/search/docs/advanced/robots/robots_txt) does state that `http://www.example.com/robots.txt` is not valid for `http://example.com/`. Based on that, I think the correct behaviour would be to fetch the robots.txt file for the preferred host and use that instead of the current one. It is probably the same in 99.99% of cases, but there is no guarantee.
