### ISSUE TITLE
Library adds port when port is never defined.

### ISSUE THREAD

**Issue by dskvr** [samclarke/robots-parser#30]
`robots-parser` appears to add a port number to the provided URL, which more often than not, breaks the ability to parse a `robots.txt` file. Or in my case, makes it completely unusable after going through a sample of a 500 URLs. There does not seem to be a way to override this.

**Comment by samclarke** [comment]
Could you give an example of where it's causing an issue?

If no port is given, it currently defaults to port 80 so that `http://example.com` URLs are treated the same as `http://example.com:80` URLs.

I've just noticed it is defaulting to port `80` with `https:`, so `https://example.com:443` URLs won't match `https://example.com` URLs, is that the issue?

**Comment by dskvr** [comment]
@samclarke Yes, an `https://` link defaults to port 80. In all honesty, however, no port should be added at all. Just take what the user gives and use that. Go ahead and normalize it if needed with `URL()` but maybe have an option to bypass.

Consider this:
1. The most likely market to utilize this module are those writing scapers, indexers, etc.
2. Therefore, they are likely going to be using URLs that are programmatically discovered. 
3. Port `80` and port `443` are defaults, many URLs in the modern age avoid defaults and the **vast majority** of websites for the last 20-25 years redirect via proxy (IE `mydomain.com` not `mydomain.com:80`). Every single website I've worked on in 20 years has a reverse proxy that results in port `80` (or `8080`, or `8181`, I think you see what I'm saying) being unreachable. 

Considering the above, I scratch my head at the decision to alter the URL provided to the method, unless normalization is truly required. And even if normalization is required, I see zero reason to append the port. If the port is needed, it would probably be provided in the argument.

**Comment by samclarke** [comment]
The default port is appended as part of the normalisation so that URLs with the default port match the URL without the default port. Not appending the port would mean less URLs would match as then `http://example.com` would not match `http://example.com:80`.

I'm not sure how this is affects proxies? The default port is the port used by clients if no port is specified. Is the issue that programmatically discovered URLs have proxy ports?

If so, the port can't be ignored as there is no guarantee that the contents of one port is the same as another.

From Google's [How to write and submit a robots.txt file](https://developers.google.com/search/docs/crawling-indexing/robots/create-robots-txt):
>* A robots.txt file applies only to paths within the protocol, host, and port where it is posted.[...]

It is possible to ignore ports entirely by doing [relative matching instead](https://github.com/samclarke/robots-parser#version-230). Relative matching may make more sense if this is being used internally.
